### PR TITLE
restructure numpad

### PR DESCRIPTION
**Pull request by Omega1902**
Numpad restructured for more ergonomic input

### CODE REVIEW

**Comment by chrshdl** [comment]
Very nice!

Could you rearrange the button labels to mimic a phone numpad like so:

1 2 3
4 5 6
7 8 9
< 0  .

I was also thinking about making the buttons bigger for easier access on a touch screen. And then putting the whole numpad under the textfield. 

What do you think?

**Comment by Omega1902** [comment]
I was rather inspired by the numpad on the keyboard, but I don't have a strong opinion on the exact layout.

I tried multiple ways to align it somehow, but I didn't succeed very well. I'll try again with different size options.

**Comment by chrshdl** [comment]
Feel free to update the README with the new view. You can take a screenshot by hitting the SPACE bar. The image will be saved in the root folder.

**Comment by Omega1902** [comment]
@chrshdl please checkout the new style - screenshot updated as suggested

**Comment by chrshdl** [comment]
@Omega1902  your PR looks good to me

**Pull request merged**
